export global Theme {
    out property <color> background_color: #121212;
    out property <color> primary_color: #007aff;
    out property <color> primary_hover: #006ce6;
    out property <color> primary_pressed: #005bb5;
    out property <color> text_color: #ffffff;
    out property <color> glass_bg: #ffffff11;
    out property <color> glass_border: #ffffff33;
    out property <color> danger_color: #ff4444;
}
